export const RoomStatus = {
  CLOSED: 'CLOSED',
  OPENED: 'OPENED',
  STARTED: 'STARTED',
  ENDED: 'ENDED'
}

export const QuizStatus = {
  TIME_OVER: 'TIME_OVER',
  ANSWER: 'ANSWER',
  LOADING: 'LOADING',
  CORRECT: 'CORRECT',
  WRONG: 'WRONG',
  SENT: 'SENT',
  UNAVAILABLE: 'UNAVAILABLE',
  ENDED: 'ENDED',
  DISCONNECTED: 'DISCONNECTED'
}